sourcecodes/AnaOkuluVeKres/AnaOkuluVeKres/Areas/Admin/Controllers/EditFeatureController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Linq;

namespace AnaOkuluVeKres.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [Route("Admin/[controller]/[action]")]
    public class EditFeatureController : Controller
    {
        private readonly Context _context;
        FeatureManager featureManager = new FeatureManager(new EfFeatureDal());

        public EditFeatureController(Context context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            int id = 1;
            var value = _context.Features.FirstOrDefault(i => i.FeatureId == id);
            return View(value);
        }
        [HttpPost]
        public ActionResult Index(Feature model)
        {
            var value = _context.Features.FirstOrDefault(i => i.FeatureId == 1);
            value.FeatureHeadTitle = model.FeatureHeadTitle;
            value.FeatureTitle1 = model.FeatureTitle1;
            value.FeatureTitle2 = model.FeatureTitle2;
            value.FeatureTitle3 = model.FeatureTitle3;
            value.FeatureTitle4 = model.FeatureTitle4;
            value.FeatureDescription1 = model.FeatureDescription1;
            value.FeatureDescription2 = model.FeatureDescription2;
            value.FeatureDescription3 = model.FeatureDescription3;
            value.FeatureDescription4 = model.FeatureDescription4;
            featureManager.TUpdate(value);
            return RedirectToAction("Index");
        }
    }
}

sourcecodes/AnaOkuluVeKres/AnaOkuluVeKres/Areas/Admin/Views/EditFeature/Index.cshtml
@model EntityLayer.Concrete.Feature

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Index", "EditFeature", FormMethod.Post))
{
    <h4>Alan Başlığı: </h4>
    @Html.TextBoxFor(x=>x.FeatureHeadTitle,new {@class ="form-control"})
    <br />
    <h4>1.Özellik Başlığı: </h4>
    @Html.TextBoxFor(x=>x.FeatureTitle1,new {@class ="form-control"})
    <br />
    <h4>Açıklaması: </h4>
    @Html.TextBoxFor(x=>x.FeatureDescription1,new {@class ="form-control"})
    <br />
    <h4>2.Özellik Başlığı: </h4>
    @Html.TextBoxFor(x=>x.FeatureTitle2,new {@class ="form-control"})
    <br />
    <h4>Açıklaması: </h4>
    @Html.TextBoxFor(x=>x.FeatureDescription2,new {@class ="form-control"})
    <br />
    <h4>3.Özellik Başlığı: </h4>
    @Html.TextBoxFor(x=>x.FeatureTitle3,new {@class ="form-control"})
    <br />
    <h4>Açıklaması: </h4>
    @Html.TextBoxFor(x=>x.FeatureDescription3,new {@class ="form-control"})
    <br />
    <h4>4.Özellik Başlığı: </h4>
    @Html.TextBoxFor(x=>x.FeatureTitle4,new {@class ="form-control"})
    <br />
    <h4>Açıklaması: </h4>
    @Html.TextBoxFor(x=>x.FeatureDescription4,new {@class ="form-control"})
    <br />
    <button class="btn btn-outline-success">Güncelle</button>
}